name: Test

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  run-unit-tests:
    name: Unit Tests
    concurrency:
      group: unit-${{ github.ref }}-${{ matrix.os }}-${{ matrix.go-version }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macOS]
    env:
      OS: ${{ matrix.os }}-latest
      GO: ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
          cache: true

      - name: Test
        run: go test -race -coverprofile unit.txt -covermode atomic ./...

      - name: Parse tag name
        id: tag
        run: |
          stripped_tag="${{ github.event.release.tag_name }}"
          echo "Stripped tag: ${stripped_tag:1}"
          echo "::set-output name=stripped_tag::${stripped_tag:1}"
        shell: bash
      - name: Use short tag
        run: echo ${{ steps.tag.outputs.stripped_tag }}

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./unit.txt
          flags: unit,${{ matrix.os }},go-${{ matrix.go-version }}
          name: unit
